# Generated by Django 3.0.3 on 2020-02-27 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hornaviationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Written',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
